Add close applications behaviour
HackAssistant/registration pull request #148
Opened 2017-09-28 22:52 UTC by casassg

Allow for applications to be closed (and close it for now)

2017-09-28 22:58 UTC, AsLogd approved these changes

2017-09-28 22:58 UTC, AsLogd commented on app/settings.py
> +                      'the opening ceremony swill be at 7:00 pm.',
swill

2017-09-28 23:05 UTC, casassg commented on app/settings.py
> +                      'the opening ceremony swill be at 7:00 pm.',
thanks! Fixed!

2017-09-29 22:53 UTC, wailingtam requested changes
❌

2017-09-29 22:53 UTC, wailingtam commented on app/templates/include/subscribe_form.html
> +    <p>Subscribe here to be the first to know when are we open applications for next edition.</p>
Subscribe here to be the first to know when `applications for the next edition are open`.

2017-09-29 22:53 UTC, wailingtam commented on register/templates/apply.html
> +        <h4 class="text-center margin-top" style="color: black;">Applications are closed. We are looking forward to welcome you next edition.</h4>
Applications are closed. We are looking forward to welcome you `on the` next edition.

2017-09-29 22:53 UTC, wailingtam commented on register/templates/phases/application.html
> +    <p>Applications have been closed.  We are looking forward to welcome you next edition.</p>
Same. 
...`on the` next edition

2017-09-29 22:53 UTC, wailingtam commented on register/templates/phases/profile.html
> +    <p>Applications have been closed. We are looking forward to welcome you next edition.</p>
same

2017-09-30 03:44 UTC, casassg commented
@wailingtam fixed

2017-09-30 11:46 UTC, wailingtam approved these changes

2017-09-30 18:37 UTC, merged