Application voting interface
HackAssistant/registration pull request #19
Opened 2017-01-02 18:22 UTC by casassg

Interface for non-admin users to vote. Similar to the previously designed. 

Shippable for now. Additional steps to be followed:

- [] Add navbar
  - [] Logout link
  - [] Change password link

2017-01-02 18:24 UTC, casassg commented
Preview: 
![voting-interface](https://cloud.githubusercontent.com/assets/6912589/21594271/e93410c0-d120-11e6-8cab-dfaea6b3f3ca.png)


Not sure about the button: "Not sure" (ah the irony) -> Behaves skipping the application

2017-01-02 21:43 UTC, ani300 requested changes
There are three comments, one on format, one on functionality and one on code clarity

2017-01-02 21:43 UTC, ani300 commented on register/templates/vote.html
> +                            {% include 'include/field.html' with desc='Name' value=app.name|add:', '|add:app.lastname %}
The format here should be either "LastName, Name" or "Name LastName" but not "Name, LastName"

2017-01-02 21:43 UTC, ani300 commented on register/views.py
> +        if request.POST.get('decline'):
For the sake of clarity, this should be an else if and not simply an if

2017-01-02 21:43 UTC, ani300 commented on register/templates/vote.html
> +                        <form action="" method="post">
Three forms... why?

2017-01-03 21:40 UTC, ani300 approved these changes

2017-01-04 13:09 UTC, casassg commented
What do you think about the not sure button? Keep or remove? @ani300

2017-01-05 07:49 UTC, ani300 commented
@casassg If we maintain it, change to "Skip this application". I find it useful if not abused, maybe limit the number of skips per user (so no one can skip more than 10 applicants or so)?

2017-01-05 09:30 UTC, casassg commented
We could put a limit, that's true. Not easy but not hard either.

On Thu, Jan 5, 2017, 08:49 Antoni <notifications@github.com> wrote:

> @casassg <https://github.com/casassg> If we maintain it, change to "Skip
> this application". I find it useful if not abused, maybe limit the number
> of skips per user (so no one can skip more than 10 applicants or so)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackupc/mercuryhack/pull/19#issuecomment-270583798>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGl6TTFajRzRwha_Nh0mL3MnJc4GgVUmks5rPKCngaJpZM4LZJuX>
> .
>

2017-01-05 15:49 UTC, ani300 commented
The other option is to just trust people to do their jobs right.
Did I just say _trust people_? What am I becoming?

2017-01-08 13:38 UTC, casassg commented
@ani300 trust the people!! For the moment we will trust people on this, it's an internal tool, so we will explain that skip is similar than negative.

2017-01-08 13:38 UTC, merged