Set Max votes for application
HackAssistant/registration pull request #290
Opened 2020-03-19 16:59 UTC by raquelpanapalen

## What this PR does / Why we need it
In the beginning of applications when an organizer is voting, s/he will vote everyone in the beginning. In order to balance votes per application it would be nice to set a max number of votes.
When an application have X votes, the application will not be showed for review to any more organizers. In addition, now a user cannot vote his/her application.

## Which issue(s) this PR fixes (optional) 

Fixes #287 

## Special notes for your reviewer (optional)

## Some questions
- [ ] I have read the contributing guidelines
- [ ] I abide by this repository Code of Conduct
- [ ] I understand that my PR won't be merged until GitHub gives a "green light"

## Additional Notes (optional)
Do you want to add anything else? We :heart: to hear your opinions!

2020-03-19 17:09 UTC, Casassarnau requested changes

2020-03-19 17:09 UTC, Casassarnau commented on organizers/views.py
> +            .exclude(user_id=self.request.user.id) \
pots posar tot això en una sola linia:
```suggestion
            .exclude(vote__user_id=self.request.user.id, user_id=self.request.user.id) \
```

2020-03-19 23:24 UTC, casassg commented on app/settings.py
> +MAX_VOTES_PER_APP = 50
```suggestion
MAX_VOTES_TO_APP = 50
```

2020-03-20 10:06 UTC, Casassarnau approved these changes

2020-03-20 16:30 UTC, casassg approved these changes

2020-03-20 16:31 UTC, merged