Blacklist
HackAssistant/registration pull request #314
Opened 2020-04-26 15:20 UTC by Ferja

## What this PR does / Why we need it
Add a blacklist structure in the system that can be edited by admins only, in order to avoid situations where a Hacker that is in the internal blacklist is accidentally accepted.

## Which issue(s) this PR fixes (optional) 
Fixes #146

## Special notes for your reviewer (optional)

## Some questions
- [ ] I have read the contributing guidelines
- [ ] I abide by this repository Code of Conduct
- [ ] I understand that my PR won't be merged until GitHub gives a "green light"

## Additional Notes (optional)
Do you want to add anything else? We :heart: to hear your opinions!

2020-05-07 14:40 UTC, Casassarnau requested changes
Could you change this please

2020-05-07 14:40 UTC, Casassarnau commented on organizers/views.py
> +class BlacklistApplicationsListView(TabsViewMixin, IsOrganizerMixin, ExportMixin, SingleTableMixin, FilterView):
This view comes from IsOrganizerMixin, this means that all organizers can acces here. In order to solve this you have to create a new minin on User/mixins.py where the function test_func will return true if the request have permisions or if is direcctor

2020-05-07 21:09 UTC, casassg commented on app/hackathon_variables.py
> +BLACKLIST_ENABLED = True
then should we set this to False by default?

2020-05-08 09:31 UTC, Ferja commented on app/hackathon_variables.py
> +BLACKLIST_ENABLED = True
Yes, we should

2020-05-09 10:59 UTC, Casassarnau approved these changes
LGTM

2020-05-09 14:08 UTC, merged